[package]
name = "attractive-numbers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primal = "0.3.1"

[package.metadata.rosettacode]
url = "http://rosettacode.org/wiki/Attractive_numbers"
