[package]
name = "random-numbers"
version = "0.1.0"
edition = "2018"

[package.metadata.rosettacode]
url = "http://rosettacode.org/wiki/Random_numbers"

[dependencies]
rand = "0.8.5"
rand_distr = "0.4.3"
